import Head from "next/head";
import useDetectPrint from "react-detect-print";

export default function Page() {
  const printing = useDetectPrint();
  const color = printing ? "blue" : "red";

  return (
    <>
      <Head>
        <title>react-detect-print example - basic</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main
        className="w-screen h-screen flex flex-col justify-center items-center border-[5vw] border-solid box-border"
        style={{ borderColor: color }}
      >
        <h1 className="text-[18vw] font-extrabold" style={{ color }}>
          {printing ? "PRINT" : "VIEW"}
        </h1>
        <p className="text-[4vw]">Try printing this page...</p>
      </main>
    </>
  );
}
