import Head from "next/head";
import useDetectPrint from "react-detect-print";
import Child from "../components/Child";

const margin = 20;

export default function Home() {
  const printing = useDetectPrint();

  return (
    <>
      <Head>
        <title>react-detect-print example - resize</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        style={{
          margin,
          borderWidth: 5,
          borderStyle: "solid",
          borderColor: "black",
          textAlign: "center",
          boxSizing: "border-box",
          MozBoxSizing: "border-box",
          WebkitBoxSizing: "border-box",
          width: printing ? 796 - margin * 2 : "auto",
        }}
      >
        <h2>Printing? {JSON.stringify(printing)}</h2>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            flexFlow: "row wrap",
          }}
        >
          <Child printing={printing} />
          <Child printing={printing} />
        </div>
      </div>
    </>
  );
}
